name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: (1) Get repository code
        uses: actions/checkout@v3
      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          dir: '${{ github.workspace }}/qt/'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'false'
      - name: (3) Create build directory
        run: mkdir ${{ github.workspace }}/build
#  build:
#    needs: [dependecies]