name: Build and Deploy
on:
  push:
    branches:
      - master
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: '5.15.2'
  ARTIFACT_NAME: 'test'
  PROJECT_NAME: 'GraduateWork'
jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3
      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{ env.SOURCE_DIR }}/qt/'
          modules: 'qtdatavis3d'
          cache: 'true'
          cache-key-prefix: 'qt-ubuntu-cache'
          setup-python: 'false'
      - name: (3) Create build directory
        run: mkdir ${{ env.SOURCE_DIR }}/build
      - name: (4) Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
             qmake ../${{ env.PROJECT_NAME }}.pro
             make
      - name: (5) Download linuxdeployqt
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
             wget -O deploy.AppImage https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
             chmod +x deploy.AppImage
             export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/gcc_64/lib/
             cp ${{ env.SOURCE_DIR }}/linux/* .
      - name: (6) Create AppImage
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
             ./deploy.AppImage ${{ env.PROJECT_NAME }} -unsupported-allow-new-glibc -appimage
             mv ${{ env.PROJECT_NAME }}*.AppImage ${{ env.ARTIFACT_NAME }}
      - name: (7) Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}_${{ env.GITHUB_CONTEXT.GITHUB_SHA }}
          path: ${{ env.SOURCE_DIR }}/build/${{ env.ARTIFACT_NAME }}
      - name: (8) Check env
        run: echo ${{ GITHUB_CONTEXT }}
          
#  Windows:
#    runs-on: windows-2019
#    steps:
#      - name: (1) Install Qt
#        uses: jurplel/install-qt-action@v3
#        with:
#          version: ${{ env.QT_VERSION }}
#          host: 'windows'
#          target: 'desktop'
#          arch: 'win64_msvc2019_64'
#          dir: '${{ env.SOURCE_DIR }}/qt/'
#          cache: 'true'
#          cache-key-prefix: 'qt-windows-cache'
#          setup-python: 'false'
#      - name: (2) Checkout repo
#        uses: actions/checkout@v3
#      - name: (3) Create build directory
#        run: mkdir ${{ env.SOURCE_DIR }}/build
#      - name: (4) Build
#        run: dir %Qt5_DIR%/


#          %Qt5_DIR%/qmake -r ${{ env.SOURCE_DIR }}\GraduateWork.pro
#          windeployqt GraduateWork.exe
