name: Build App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: (2) Checkout repo
      uses: actions/checkout@v3
    - name: Install Qt 5.15.2 on Ubuntu
      uses: jurplel/install-qt@v3
      with:
        version: '5.15.2'
        target: Desktop
        distro: 'ubuntu-20.04'
    - name: Build App on Ubuntu
      run: qmake && make

  build-windows:
    runs-on: windows-latest
    steps:
    - name: (2) Checkout repo
      uses: actions/checkout@v3
    - name: Install Qt 5.15.2 on Windows
      uses: jurplel/install-qt@v3
      with:
        version: '5.15.2'
        target: Desktop
        distro: 'windows'
    - name: Build App on Windows
      run: qmake && nmake
