name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  dependecies:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
#          dir: '${{ github.workspace }}/qt/'
#          #modules:
#          cache: 'true'
#          cache-key-prefix: 'install-qt-action'
#          #setup-python: 'false'
      - name: Get repository code
        uses: actions/checkout@v3
#  build:
#    needs: [dependecies]