name: Build and Deploy
on:
  push:
    branches:
      - master
env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 5.15.2
  ARTIFACT_NAME: PopovDs_9304_GraduateWork
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: (1) Get repository code
        uses: actions/checkout@v3
      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
          dir: ${{ runner.temp }}
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          #setup-python: 'false'
      - name: (3) Create build directory
        run: mkdir ${{ runner.temp }}\build
#  build:
#    needs: [dependecies]